#!/usr/bin/python
#-*- coding=utf-8 -*-

emolist = [{"emo_detail":"0023 20e3","tags":["hash key","#"],"emo_type":1},
{"emo_detail":"0030 20e3","tags":["keycap 0","0"],"emo_type":1},
{"emo_detail":"0031 20e3","tags":["keycap 1","1"],"emo_type":1},
{"emo_detail":"0032 20e3","tags":["keycap 2","2"],"emo_type":1},
{"emo_detail":"0033 20e3","tags":["keycap 3","3"],"emo_type":1},
{"emo_detail":"0034 20e3","tags":["keycap 4","4"],"emo_type":1},
{"emo_detail":"0035 20e3","tags":["keycap 5","5"],"emo_type":1},
{"emo_detail":"0036 20e3","tags":["keycap 6","6"],"emo_type":1},
{"emo_detail":"0037 20e3","tags":["keycap 7","7"],"emo_type":1},
{"emo_detail":"0038 20e3","tags":["keycap 8","8"],"emo_type":1},
{"emo_detail":"0039 20e3","tags":["keycap 9","9"],"emo_type":1},
{"emo_detail":"00a9","tags":["copyright sign","版权","copyright"],"emo_type":1},
{"emo_detail":"00ae","tags":["registered sign","注册商标"],"emo_type":1},
{"emo_detail":"1f004","tags":["mahjong tile red dragon","红中"],"emo_type":1},
{"emo_detail":"1f0cf","tags":["playing card black joker","小王"],"emo_type":1},
{"emo_detail":"1f170","tags":["negative squared latin capital letter a","A型血","血型A"],"emo_type":1},
{"emo_detail":"1f171","tags":["negative squared latin capital letter b","B型血","血型B"],"emo_type":1},
{"emo_detail":"1f17e","tags":["negative squared latin capital letter o","0型血","血型O"],"emo_type":1},
{"emo_detail":"1f17f","tags":["negative squared latin capital letter p","P"],"emo_type":1},
{"emo_detail":"1f18e","tags":["negative squared ab","AB型血","血型AB"],"emo_type":1},
{"emo_detail":"1f191","tags":["squared cl","control键","CL键"],"emo_type":1},
{"emo_detail":"1f192","tags":["squared cool","cool"],"emo_type":1},
{"emo_detail":"1f193","tags":["squared free","free"],"emo_type":1},
{"emo_detail":"1f194","tags":["squared id","ID"],"emo_type":1},
{"emo_detail":"1f195","tags":["squared new","new"],"emo_type":1},
{"emo_detail":"1f196","tags":["squared ng","NG"],"emo_type":1},
{"emo_detail":"1f197","tags":["squared ok","OK"],"emo_type":1},
{"emo_detail":"1f198","tags":["squared sos","SOS","求救"],"emo_type":1},
{"emo_detail":"1f199","tags":["squared up with exclamation mark","UP"],"emo_type":1},
{"emo_detail":"1f19a","tags":["squared vs","VS","V.S."],"emo_type":1},
{"emo_detail":"1f1e8 1f1f3","tags":["regional indicator symbol letters cn","中国","中国国旗","国旗"],"emo_type":1},
{"emo_detail":"1f1e9 1f1ea","tags":["regional indicator symbol letters de","德国","德国国旗","国旗"],"emo_type":1},
{"emo_detail":"1f1ea 1f1f8","tags":["regional indicator symbol letters es","西班牙","西班牙国旗","国旗"],"emo_type":1},
{"emo_detail":"1f1eb 1f1f7","tags":["regional indicator symbol letters fr","法国","法国国旗","国旗"],"emo_type":1},
{"emo_detail":"1f1ec 1f1e7","tags":["regional indicator symbol letters gb","英国","英国国旗","国旗"],"emo_type":1},
{"emo_detail":"1f1ee 1f1f9","tags":["regional indicator symbol letters it","意大利","意大利国旗","国旗"],"emo_type":1},
{"emo_detail":"1f1ef 1f1f5","tags":["regional indicator symbol letters jp","日本","日本国旗","国旗"],"emo_type":1},
{"emo_detail":"1f1f0 1f1f7","tags":["regional indicator symbol letters kr","韩国","韩国国旗","国旗"],"emo_type":1},
{"emo_detail":"1f1f7 1f1fa","tags":["regional indicator symbol letters ru","俄罗斯","俄罗斯国旗","国旗"],"emo_type":1},
{"emo_detail":"1f1fa 1f1f8","tags":["regional indicator symbol letters us","美国","美国国旗","国旗"],"emo_type":1},
{"emo_detail":"1f201","tags":["squared katakana koko"],"emo_type":1},
{"emo_detail":"1f202","tags":["squared katakana sa"],"emo_type":1},
{"emo_detail":"1f21a","tags":["squared cjk unified ideograph-7121","无"],"emo_type":1},
{"emo_detail":"1f22f","tags":["squared cjk unified ideograph-6307","指"],"emo_type":1},
{"emo_detail":"1f232","tags":["squared cjk unified ideograph-7981","禁"],"emo_type":1},
{"emo_detail":"1f233","tags":["squared cjk unified ideograph-7a7a","空"],"emo_type":1},
{"emo_detail":"1f234","tags":["squared cjk unified ideograph-5408","合"],"emo_type":1},
{"emo_detail":"1f235","tags":["squared cjk unified ideograph-6e80","满"],"emo_type":1},
{"emo_detail":"1f236","tags":["squared cjk unified ideograph-6709","有"],"emo_type":1},
{"emo_detail":"1f237","tags":["squared cjk unified ideograph-6708","月"],"emo_type":1},
{"emo_detail":"1f238","tags":["squared cjk unified ideograph-7533","申"],"emo_type":1},
{"emo_detail":"1f239","tags":["squared cjk unified ideograph-5272","割"],"emo_type":1},
{"emo_detail":"1f23a","tags":["squared cjk unified ideograph-55b6"],"emo_type":1},
{"emo_detail":"1f250","tags":["circled ideograph advantage","得"],"emo_type":1},
{"emo_detail":"1f251","tags":["circled ideograph accept","可"],"emo_type":1},
{"emo_detail":"1f300","tags":["cyclone","旋风","龙卷风","自然"],"emo_type":1},
{"emo_detail":"1f301","tags":["foggy","雾","自然"],"emo_type":1},
{"emo_detail":"1f302","tags":["closed umbrella","伞","雨伞","自然"],"emo_type":1},
{"emo_detail":"1f303","tags":["night with stars","星星","夜空","自然","自然"],"emo_type":1},
{"emo_detail":"1f304","tags":["sunrise over mountains","日出","自然","自然"],"emo_type":1},
{"emo_detail":"1f305","tags":["sunrise","日出","自然"],"emo_type":1},
{"emo_detail":"1f306","tags":["cityscape at dusk","傍晚","黄昏","自然"],"emo_type":1},
{"emo_detail":"1f307","tags":["sunset over buildings","日落","夕阳","自然"],"emo_type":1},
{"emo_detail":"1f308","tags":["rainbow","彩虹","自然"],"emo_type":1},
{"emo_detail":"1f309","tags":["bridge at night","桥","自然"],"emo_type":1},
{"emo_detail":"1f30a","tags":["water wave","浪花","波浪","自然"],"emo_type":1},
{"emo_detail":"1f30b","tags":["volcano","火山","自然"],"emo_type":1},
{"emo_detail":"1f30c","tags":["milky way","银河","自然"],"emo_type":1},
{"emo_detail":"1f30d","tags":["earth globe europe-africa","地球","自然"],"emo_type":1},
{"emo_detail":"1f30e","tags":["earth globe americas","地球","自然"],"emo_type":1},
{"emo_detail":"1f30f","tags":["earth globe asia-australia","地球","自然"],"emo_type":1},
{"emo_detail":"1f310","tags":["globe with meridians","地球仪","地球","自然"],"emo_type":1},
{"emo_detail":"1f311","tags":["new moon symbol","新月","自然"],"emo_type":1},
{"emo_detail":"1f312","tags":["waxing crescent moon symbol","新月","自然"],"emo_type":1},
{"emo_detail":"1f313","tags":["first quarter moon symbol","上弦月","自然"],"emo_type":1},
{"emo_detail":"1f314","tags":["waxing gibbous moon symbol","盈凸月","自然"],"emo_type":1},
{"emo_detail":"1f315","tags":["full moon symbol","圆月","自然"],"emo_type":1},
{"emo_detail":"1f316","tags":["waning gibbous moon symbol"],"emo_type":1},
{"emo_detail":"1f317","tags":["last quarter moon symbol"],"emo_type":1},
{"emo_detail":"1f318","tags":["waning crescent moon symbol"],"emo_type":1},
{"emo_detail":"1f319","tags":["crescent moon","新月","自然"],"emo_type":1},
{"emo_detail":"1f31a","tags":["new moon with face"],"emo_type":1},
{"emo_detail":"1f31b","tags":["first quarter moon with face","月亮","自然"],"emo_type":1},
{"emo_detail":"1f31c","tags":["last quarter moon with face","月亮","自然"],"emo_type":1},
{"emo_detail":"1f31d","tags":["full moon with face","月亮","自然"],"emo_type":1},
{"emo_detail":"1f31e","tags":["sun with face","太阳","自然"],"emo_type":1},
{"emo_detail":"1f31f","tags":["glowing star","流星","自然"],"emo_type":1},
{"emo_detail":"1f320","tags":["shooting star","问号","？","?"],"emo_type":1},
{"emo_detail":"1f330","tags":["chestnut","栗子","食物"],"emo_type":1},
{"emo_detail":"1f331","tags":["seedling","幼苗","自然"],"emo_type":1},
{"emo_detail":"1f334","tags":["palm tree","棕榈树","自然"],"emo_type":1},
{"emo_detail":"1f335","tags":["cactus","仙人掌","自然"],"emo_type":1},
{"emo_detail":"1f337","tags":["tulip","郁金香","自然"],"emo_type":1},
{"emo_detail":"1f338","tags":["cherry blossom","樱花","自然"],"emo_type":1},
{"emo_detail":"1f339","tags":["rose","玫瑰","自然"],"emo_type":1},
{"emo_detail":"1f33a","tags":["hibiscus","芙蓉","自然"],"emo_type":1},
{"emo_detail":"1f33b","tags":["sunflower","向日葵","太阳花","自然"],"emo_type":1},
{"emo_detail":"1f33c","tags":["blossom","花","自然"],"emo_type":1},
{"emo_detail":"1f33d","tags":["ear of maize","玉米","自然"],"emo_type":1},
{"emo_detail":"1f33e","tags":["ear of rice","水稻","自然"],"emo_type":1},
{"emo_detail":"1f33f","tags":["herb","草","自然"],"emo_type":1},
{"emo_detail":"1f340","tags":["four leaf clover","四叶苜蓿","自然"],"emo_type":1},
{"emo_detail":"1f341","tags":["maple leaf","枫叶","自然"],"emo_type":1},
{"emo_detail":"1f342","tags":["fallen leaf","落叶","自然"],"emo_type":1},
{"emo_detail":"1f343","tags":["leaf fluttering in wind","飞舞的叶子","自然"],"emo_type":1},
{"emo_detail":"1f344","tags":["mushroom","蘑菇","食物"],"emo_type":1},
{"emo_detail":"1f345","tags":["tomato","番茄","食物"],"emo_type":1},
{"emo_detail":"1f346","tags":["aubergine","茄子","食物"],"emo_type":1},
{"emo_detail":"1f347","tags":["grapes","葡萄","食物"],"emo_type":1},
{"emo_detail":"1f348","tags":["melon","瓜","食物"],"emo_type":1},
{"emo_detail":"1f349","tags":["watermelon","西瓜","食物"],"emo_type":1},
{"emo_detail":"1f34a","tags":["tangerine","橘子","食物"],"emo_type":1},
{"emo_detail":"1f34c","tags":["banana","香蕉","食物"],"emo_type":1},
{"emo_detail":"1f34d","tags":["pineapple","菠萝","食物"],"emo_type":1},
{"emo_detail":"1f34e","tags":["red apple","红苹果","食物"],"emo_type":1},
{"emo_detail":"1f34f","tags":["green apple","青苹果","食物"],"emo_type":1},
{"emo_detail":"1f350","tags":["pear","梨子","梨","食物"],"emo_type":1},
{"emo_detail":"1f351","tags":["peach","桃子","食物"],"emo_type":1},
{"emo_detail":"1f352","tags":["cherries","樱桃","食物"],"emo_type":1},
{"emo_detail":"1f353","tags":["strawberry","草莓","食物"],"emo_type":1},
{"emo_detail":"1f354","tags":["hamburger","汉堡包","食物","食物"],"emo_type":1},
{"emo_detail":"1f355","tags":["slice of pizza","比萨","pizza","食物"],"emo_type":1},
{"emo_detail":"1f356","tags":["meat on bone","肉棒","食物"],"emo_type":1},
{"emo_detail":"1f357","tags":["poultry leg","鸡腿","食物"],"emo_type":1},
{"emo_detail":"1f358","tags":["rice cracker","米饼","食物"],"emo_type":1},
{"emo_detail":"1f359","tags":["rice ball","饭团","食物"],"emo_type":1},
{"emo_detail":"1f35a","tags":["cooked rice","米饭","食物"],"emo_type":1},
{"emo_detail":"1f35b","tags":["curry and rice","咖喱饭","食物"],"emo_type":1},
{"emo_detail":"1f35c","tags":["steaming bowl","汤面","食物","食物"],"emo_type":1},
{"emo_detail":"1f35d","tags":["spaghetti","意大利面条","食物"],"emo_type":1},
{"emo_detail":"1f35e","tags":["bread","面包","食物"],"emo_type":1},
{"emo_detail":"1f35f","tags":["french fries","薯条","食物"],"emo_type":1},
{"emo_detail":"1f360","tags":["roasted sweet potato","烤地瓜","食物"],"emo_type":1},
{"emo_detail":"1f361","tags":["dango","糯米团","食物"],"emo_type":1},
{"emo_detail":"1f362","tags":["oden","关东煮","食物"],"emo_type":1},
{"emo_detail":"1f363","tags":["sushi","寿司","食物"],"emo_type":1},
{"emo_detail":"1f364","tags":["fried shrimp","炸虾","食物"],"emo_type":1},
{"emo_detail":"1f365","tags":["fish cake with swirl design","鱼蛋糕","食物"],"emo_type":1},
{"emo_detail":"1f366","tags":["soft ice cream","冰激凌","食物"],"emo_type":1},
{"emo_detail":"1f367","tags":["shaved ice","刨冰","食物"],"emo_type":1},
{"emo_detail":"1f368","tags":["ice cream","冰激凌","食物"],"emo_type":1},
{"emo_detail":"1f369","tags":["doughnut","甜甜圈","食物"],"emo_type":1},
{"emo_detail":"1f36a","tags":["cookie","饼干","食物"],"emo_type":1},
{"emo_detail":"1f36b","tags":["chocolate bar","巧克力","食物"],"emo_type":1},
{"emo_detail":"1f36c","tags":["candy","糖果","食物"],"emo_type":1},
{"emo_detail":"1f36d","tags":["lollipop","棒棒糖","食物"],"emo_type":1},
{"emo_detail":"1f36e","tags":["custard","蛋羹","蛋奶糊","牛奶沙司","食物"],"emo_type":1},
{"emo_detail":"1f36f","tags":["honey pot","火锅","食物"],"emo_type":1},
{"emo_detail":"1f370","tags":["shortcake","蛋糕","食物"],"emo_type":1},
{"emo_detail":"1f371","tags":["bento box","盒饭","食物"],"emo_type":1},
{"emo_detail":"1f372","tags":["pot of food","热气腾腾","食物"],"emo_type":1},
{"emo_detail":"1f373","tags":["cooking","烹饪","食物"],"emo_type":1},
{"emo_detail":"1f374","tags":["fork and knife","刀叉","餐具"],"emo_type":1},
{"emo_detail":"1f375","tags":["teacup without handle","茶杯","餐具"],"emo_type":1},
{"emo_detail":"1f376","tags":["sake bottle and cup","清酒","饮料"],"emo_type":1},
{"emo_detail":"1f377","tags":["wine glass","酒杯","饮料"],"emo_type":1},
{"emo_detail":"1f378","tags":["cocktail glass","鸡尾酒","酒杯","饮料"],"emo_type":1},
{"emo_detail":"1f379","tags":["tropical drink","热带饮料","饮料"],"emo_type":1},
{"emo_detail":"1f37a","tags":["beer mug","扎啤","啤酒","饮料"],"emo_type":1},
{"emo_detail":"1f37b","tags":["clinking beer mugs","碰杯","啤酒","饮料"],"emo_type":1},
{"emo_detail":"1f37c","tags":["babby bottle","奶瓶"],"emo_type":1},
{"emo_detail":"1f380","tags":["ribbon","丝带"],"emo_type":1},
{"emo_detail":"1f381","tags":["wrapped present","礼物","庆祝"],"emo_type":1},
{"emo_detail":"1f382","tags":["birthday cake","生日","庆祝","食物"],"emo_type":1},
{"emo_detail":"1f383","tags":["jack-o-lantern","南瓜","食物"],"emo_type":1},
{"emo_detail":"1f384","tags":["christmas tree","圣诞树"],"emo_type":1},
{"emo_detail":"1f385","tags":["father christmas","圣诞老人"],"emo_type":1},
{"emo_detail":"1f386","tags":["fireworks","焰火","自然"],"emo_type":1},
{"emo_detail":"1f387","tags":["firework sparkler","烟火","自然"],"emo_type":1},
{"emo_detail":"1f388","tags":["balloon","气球"],"emo_type":1},
{"emo_detail":"1f389","tags":["party popper","派对","特色装饰品"],"emo_type":1},
{"emo_detail":"1f38a","tags":["confetti ball","五彩纸屑球","特色装饰品"],"emo_type":1},
{"emo_detail":"1f38b","tags":["tanabata tree","七夕树","特色装饰品"],"emo_type":1},
{"emo_detail":"1f38c","tags":["crossed flags","旗帜","特色装饰品"],"emo_type":1},
{"emo_detail":"1f38d","tags":["pine decoration","松木装饰","特色装饰品"],"emo_type":1},
{"emo_detail":"1f38e","tags":["japanese dolls","日本玩偶","特色装饰品"],"emo_type":1},
{"emo_detail":"1f38f","tags":["carp streamer","鲤鱼旗","特色装饰品"],"emo_type":1},
{"emo_detail":"1f390","tags":["wind chime","风铃","特色装饰品"],"emo_type":1},
{"emo_detail":"1f391","tags":["moon viewing ceremony","观月","自然"],"emo_type":1},
{"emo_detail":"1f392","tags":["school satchel","书包"],"emo_type":1},
{"emo_detail":"1f393","tags":["graduation cap","毕业帽"],"emo_type":1},
{"emo_detail":"1f3a0","tags":["carousel horse","旋转木马"],"emo_type":1},
{"emo_detail":"1f3a1","tags":["ferris wheel","摩天轮"],"emo_type":1},
{"emo_detail":"1f3a2","tags":["roller coaster","过山车"],"emo_type":1},
{"emo_detail":"1f3a3","tags":["fishing pole and fish","钓鱼杆","钓鱼"],"emo_type":1},
{"emo_detail":"1f3a4","tags":["microphone","麦克风"],"emo_type":1},
{"emo_detail":"1f3a5","tags":["movie camera","摄像机"],"emo_type":1},
{"emo_detail":"1f3a6","tags":["cinema","电影院"],"emo_type":1},
{"emo_detail":"1f3a7","tags":["headphone","耳机"],"emo_type":1},
{"emo_detail":"1f3a8","tags":["artist palette","调色板"],"emo_type":1},
{"emo_detail":"1f3a9","tags":["top hat","礼帽"],"emo_type":1},
{"emo_detail":"1f3aa","tags":["circus tent","马戏团的帐篷","帐篷"],"emo_type":1},
{"emo_detail":"1f3ab","tags":["ticket","票"],"emo_type":1},
{"emo_detail":"1f3ac","tags":["clapper board","电影"],"emo_type":1},
{"emo_detail":"1f3ad","tags":["performing arts","表演艺术"],"emo_type":1},
{"emo_detail":"1f3ae","tags":["video game","视频游戏","游戏"],"emo_type":1},
{"emo_detail":"1f3af","tags":["direct hit","命中","射箭"],"emo_type":1},
{"emo_detail":"1f3b0","tags":["slot machine","老虎机"],"emo_type":1},
{"emo_detail":"1f3b1","tags":["billiards","台球"],"emo_type":1},
{"emo_detail":"1f3b2","tags":["game die","骰子","色子"],"emo_type":1},
{"emo_detail":"1f3b3","tags":["bowling","保龄球"],"emo_type":1},
{"emo_detail":"1f3b4","tags":["flower playing cards","花扑克牌"],"emo_type":1},
{"emo_detail":"1f3b5","tags":["musical note","音符","音乐"],"emo_type":1},
{"emo_detail":"1f3b6","tags":["multiple musical notes","多个音符"],"emo_type":1},
{"emo_detail":"1f3b7","tags":["saxophone","萨克斯"],"emo_type":1},
{"emo_detail":"1f3b8","tags":["guitar","吉他"],"emo_type":1},
{"emo_detail":"1f3b9","tags":["musical keyboard","键盘"],"emo_type":1},
{"emo_detail":"1f3ba","tags":["trumpet","喇叭"],"emo_type":1},
{"emo_detail":"1f3bb","tags":["violin","小提琴"],"emo_type":1},
{"emo_detail":"1f3bc","tags":["musical score","乐谱","五线谱"],"emo_type":1},
{"emo_detail":"1f3bd","tags":["running shirt with sash"],"emo_type":1},
{"emo_detail":"1f3be","tags":["tennis racquet and ball","网球"],"emo_type":1},
{"emo_detail":"1f3bf","tags":["ski and ski boot","滑雪板"],"emo_type":1},
{"emo_detail":"1f3c0","tags":["basketball and hoop","篮球","运动"],"emo_type":1},
{"emo_detail":"1f3c1","tags":["chequered flag","格子旗"],"emo_type":1},
{"emo_detail":"1f3c2","tags":["snowboarder","滑雪"],"emo_type":1},
{"emo_detail":"1f3c3","tags":["runner","跑步"],"emo_type":1},
{"emo_detail":"1f3c4","tags":["surfer","冲浪"],"emo_type":1},
{"emo_detail":"1f3c6","tags":["trophy","奖杯"],"emo_type":1},
{"emo_detail":"1f3c7","tags":["horse racer","赛马","骑马"],"emo_type":1},
{"emo_detail":"1f3c8","tags":["american football","橄榄球"],"emo_type":1},
{"emo_detail":"1f3c9","tags":["rugby football","橄榄球"],"emo_type":1},
{"emo_detail":"1f3ca","tags":["swimmer","游泳","运动"],"emo_type":1},
{"emo_detail":"1f3e0","tags":["house building","房子","楼房","建筑"],"emo_type":1},
{"emo_detail":"1f3e1","tags":["house with garden","房子"],"emo_type":1},
{"emo_detail":"1f3e2","tags":["office building","大楼","办公楼","建筑"],"emo_type":1},
{"emo_detail":"1f3e3","tags":["japanese post office","日式邮局","邮局"],"emo_type":1},
{"emo_detail":"1f3e4","tags":["european post office","欧式邮局","邮局"],"emo_type":1},
{"emo_detail":"1f3e5","tags":["hospital","医院"],"emo_type":1},
{"emo_detail":"1f3e6","tags":["bank","银行"],"emo_type":1},
{"emo_detail":"1f3e7","tags":["automated teller machine","自动取款机","自动柜员机","ATM","取款机"],"emo_type":1},
{"emo_detail":"1f3e8","tags":["hotel","酒店"],"emo_type":1},
{"emo_detail":"1f3e9","tags":["love hotel","情侣酒店","爱情旅馆"],"emo_type":1},
{"emo_detail":"1f3ea","tags":["convenience store","便利店"],"emo_type":1},
{"emo_detail":"1f3eb","tags":["school","学校"],"emo_type":1},
{"emo_detail":"1f3ec","tags":["department store","商店","百货商店"],"emo_type":1},
{"emo_detail":"1f3ed","tags":["factory","工厂"],"emo_type":1},
{"emo_detail":"1f3ee","tags":["izakaya lantern","灯笼"],"emo_type":1},
{"emo_detail":"1f3ef","tags":["japanese castle","城堡"],"emo_type":1},
{"emo_detail":"1f3f0","tags":["european castle","城堡"],"emo_type":1},
{"emo_detail":"1f400","tags":["rat","大老鼠","动物"],"emo_type":1},
{"emo_detail":"1f401","tags":["mouse","老鼠","动物"],"emo_type":1},
{"emo_detail":"1f402","tags":["ox","公牛","牛","动物"],"emo_type":1},
{"emo_detail":"1f403","tags":["water buffalo","水牛","动物"],"emo_type":1},
{"emo_detail":"1f404","tags":["cow","奶牛","动物"],"emo_type":1},
{"emo_detail":"1f405","tags":["tiger","老虎","动物"],"emo_type":1},
{"emo_detail":"1f406","tags":["leopard","豹","动物"],"emo_type":1},
{"emo_detail":"1f407","tags":["rabbit","兔子","动物"],"emo_type":1},
{"emo_detail":"1f408","tags":["cat","猫","动物"],"emo_type":1},
{"emo_detail":"1f409","tags":["dragon","龙","动物"],"emo_type":1},
{"emo_detail":"1f40a","tags":["crocodile","鳄鱼","动物"],"emo_type":1},
{"emo_detail":"1f40b","tags":["whale","鲸鱼","动物"],"emo_type":1},
{"emo_detail":"1f40c","tags":["snail","蜗牛","动物"],"emo_type":1},
{"emo_detail":"1f40d","tags":["snake","蛇","动物"],"emo_type":1},
{"emo_detail":"1f40e","tags":["horse","马","动物"],"emo_type":1},
{"emo_detail":"1f40f","tags":["ram","公羊","动物"],"emo_type":1},
{"emo_detail":"1f410","tags":["goat","绵羊","动物"],"emo_type":1},
{"emo_detail":"1f411","tags":["sheep","山羊","羊","动物"],"emo_type":1},
{"emo_detail":"1f412","tags":["monkey","猴子","动物"],"emo_type":1},
{"emo_detail":"1f413","tags":["rooster","公鸡","动物"],"emo_type":1},
{"emo_detail":"1f414","tags":["chicken","鸡","动物"],"emo_type":1},
{"emo_detail":"1f415","tags":["dog","狗","动物"],"emo_type":1},
{"emo_detail":"1f416","tags":["pig","猪","动物"],"emo_type":1},
{"emo_detail":"1f417","tags":["boar","野猪","动物"],"emo_type":1},
{"emo_detail":"1f418","tags":["elephant","大象","动物"],"emo_type":1},
{"emo_detail":"1f419","tags":["octopus","章鱼","动物"],"emo_type":1},
{"emo_detail":"1f41a","tags":["spiral shell","螺蛳","螺蛳壳","动物"],"emo_type":1},
{"emo_detail":"1f41b","tags":["bug","臭虫","虫子","动物"],"emo_type":1},
{"emo_detail":"1f41c","tags":["ant","蚂蚁","动物"],"emo_type":1},
{"emo_detail":"1f41d","tags":["honeybee","蜜蜂","动物"],"emo_type":1},
{"emo_detail":"1f41e","tags":["lady beetle","瓢虫","动物"],"emo_type":1},
{"emo_detail":"1f41f","tags":["fish","鱼","动物"],"emo_type":1},
{"emo_detail":"1f420","tags":["tropical fish","热带鱼","动物"],"emo_type":1},
{"emo_detail":"1f421","tags":["blowfish","河豚","动物"],"emo_type":1},
{"emo_detail":"1f422","tags":["turtle","乌龟","动物"],"emo_type":1},
{"emo_detail":"1f423","tags":["hatching chick","孵化小鸡","动物"],"emo_type":1},
{"emo_detail":"1f424","tags":["baby chick","小鸡","动物"],"emo_type":1},
{"emo_detail":"1f425","tags":["front-facing baby chick","小鸡","动物"],"emo_type":1},
{"emo_detail":"1f426","tags":["bird","鸟","动物"],"emo_type":1},
{"emo_detail":"1f427","tags":["penguin","企鹅","动物"],"emo_type":1},
{"emo_detail":"1f428","tags":["koala","考拉","动物"],"emo_type":1},
{"emo_detail":"1f429","tags":["poodle","贵宾犬","动物"],"emo_type":1},
{"emo_detail":"1f42a","tags":["dromedary camel","单峰驼","动物"],"emo_type":1},
{"emo_detail":"1f42b","tags":["bactrian camel","双峰驼","骆驼","动物"],"emo_type":1},
{"emo_detail":"1f42c","tags":["dolphin","海豚","动物"],"emo_type":1},
{"emo_detail":"1f42d","tags":["mouse face","老鼠","动物"],"emo_type":1},
{"emo_detail":"1f42e","tags":["cow face","奶牛","动物"],"emo_type":1},
{"emo_detail":"1f42f","tags":["tiger face","老虎","动物"],"emo_type":1},
{"emo_detail":"1f430","tags":["rabbit face","兔子","动物"],"emo_type":1},
{"emo_detail":"1f431","tags":["cat face","猫","动物"],"emo_type":1},
{"emo_detail":"1f432","tags":["dragon face","龙","动物"],"emo_type":1},
{"emo_detail":"1f433","tags":["spouting whale","喷射鲸鱼","动物"],"emo_type":1},
{"emo_detail":"1f434","tags":["horse face","马","动物"],"emo_type":1},
{"emo_detail":"1f435","tags":["monkey face","猴子","动物"],"emo_type":1},
{"emo_detail":"1f436","tags":["dog face","狗","小狗","动物"],"emo_type":1},
{"emo_detail":"1f437","tags":["pig face","猪","动物"],"emo_type":1},
{"emo_detail":"1f438","tags":["frog face","青蛙","动物"],"emo_type":1},
{"emo_detail":"1f439","tags":["hamster face","仓鼠","动物"],"emo_type":1},
{"emo_detail":"1f43a","tags":["wolf face","狼","动物"],"emo_type":1},
{"emo_detail":"1f43b","tags":["bear face","熊","动物"],"emo_type":1},
{"emo_detail":"1f43c","tags":["panda face","大熊猫","熊猫","动物"],"emo_type":1},
{"emo_detail":"1f43d","tags":["pig nose","猪鼻子","动物"],"emo_type":1},
{"emo_detail":"1f43e","tags":["paw prints","爪印","动物"],"emo_type":1},
{"emo_detail":"1f440","tags":["eyes","眼睛","五官"],"emo_type":1},
{"emo_detail":"1f442","tags":["ear","耳朵","五官"],"emo_type":1},
{"emo_detail":"1f443","tags":["nose","鼻子","五官"],"emo_type":1},
{"emo_detail":"1f444","tags":["mouth","口","五官"],"emo_type":1},
{"emo_detail":"1f445","tags":["tongue","舌头","五官"],"emo_type":1},
{"emo_detail":"1f446","tags":["white up pointing backhand index","上"],"emo_type":1},
{"emo_detail":"1f447","tags":["white down pointing backhand index","下"],"emo_type":1},
{"emo_detail":"1f448","tags":["white left pointing backhand index","左"],"emo_type":1},
{"emo_detail":"1f449","tags":["white right pointing backhand index","右"],"emo_type":1},
{"emo_detail":"1f44a","tags":["fisted hand sign","拳头","重拳"],"emo_type":1},
{"emo_detail":"1f44b","tags":["waving hand sign","招手"],"emo_type":1},
{"emo_detail":"1f44c","tags":["ok hand sign","OK"],"emo_type":1},
{"emo_detail":"1f44d","tags":["thumbs up sign","赞"],"emo_type":1},
{"emo_detail":"1f44e","tags":["thumbs down sign","弱","踩"],"emo_type":1},
{"emo_detail":"1f44f","tags":["clapping hands sign","拍手","鼓掌"],"emo_type":1},
{"emo_detail":"1f450","tags":["open hands sign","打开手"],"emo_type":1},
{"emo_detail":"1f451","tags":["crown","皇冠","服饰"],"emo_type":1},
{"emo_detail":"1f452","tags":["womans hat","女帽","草帽","女士帽","礼帽","服饰"],"emo_type":1},
{"emo_detail":"1f453","tags":["eyeglasses","眼镜","服饰"],"emo_type":1},
{"emo_detail":"1f454","tags":["necktie","领带","服装","服饰"],"emo_type":1},
{"emo_detail":"1f455","tags":["t-shirt","t恤","服装","服饰"],"emo_type":1},
{"emo_detail":"1f456","tags":["jeans","牛仔裤","服饰"],"emo_type":1},
{"emo_detail":"1f457","tags":["dress","衣服","裙子","服饰"],"emo_type":1},
{"emo_detail":"1f458","tags":["kimono","和服","服饰"],"emo_type":1},
{"emo_detail":"1f459","tags":["bikini","比基尼","服饰"],"emo_type":1},
{"emo_detail":"1f45a","tags":["womans clothes","女装","服饰"],"emo_type":1},
{"emo_detail":"1f45b","tags":["purse","钱包","服饰"],"emo_type":1},
{"emo_detail":"1f45c","tags":["handbag","手提包","服饰"],"emo_type":1},
{"emo_detail":"1f45d","tags":["pouch","袋","服饰"],"emo_type":1},
{"emo_detail":"1f45e","tags":["mans shoe","男鞋","服饰"],"emo_type":1},
{"emo_detail":"1f45f","tags":["athletic shoe","运动鞋","服饰"],"emo_type":1},
{"emo_detail":"1f460","tags":["high-heeled shoe","高跟鞋","服饰"],"emo_type":1},
{"emo_detail":"1f461","tags":["womans sandal","女士凉鞋","凉鞋","服饰"],"emo_type":1},
{"emo_detail":"1f462","tags":["womans boots","女士长靴","靴子","长靴","服饰"],"emo_type":1},
{"emo_detail":"1f463","tags":["footprints","脚印"],"emo_type":1},
{"emo_detail":"1f464","tags":["bust in silhouette","单人","人","用户","人物"],"emo_type":1},
{"emo_detail":"1f465","tags":["busts in silhouette","双人","人物"],"emo_type":1},
{"emo_detail":"1f466","tags":["boy","男孩","人物"],"emo_type":1},
{"emo_detail":"1f467","tags":["girl","女孩","人物"],"emo_type":1},
{"emo_detail":"1f468","tags":["man","男人","人物"],"emo_type":1},
{"emo_detail":"1f469","tags":["woman","女人","人物"],"emo_type":1},
{"emo_detail":"1f46a","tags":["family","家庭","人物"],"emo_type":1},
{"emo_detail":"1f46b","tags":["man and woman holding hands","情侣","夫妻","人物"],"emo_type":1},
{"emo_detail":"1f46e","tags":["police officer","警察","人物"],"emo_type":1},
{"emo_detail":"1f46f","tags":["woman with bunny ears","兔女郎","人物"],"emo_type":1},
{"emo_detail":"1f470","tags":["bride with veil","新娘","人物"],"emo_type":1},
{"emo_detail":"1f471","tags":["person with blond hair","金发碧眼","人物"],"emo_type":1},
{"emo_detail":"1f472","tags":["man with gua pi mao","瓜皮帽男","人物"],"emo_type":1},
{"emo_detail":"1f473","tags":["man with turban","头巾男","人物"],"emo_type":1},
{"emo_detail":"1f474","tags":["older man","老头","老人","人物"],"emo_type":1},
{"emo_detail":"1f475","tags":["older woman","老太太","老大妈","人物"],"emo_type":1},
{"emo_detail":"1f476","tags":["baby","婴儿","人物"],"emo_type":1},
{"emo_detail":"1f477","tags":["construction worker","建筑工人","人物"],"emo_type":1},
{"emo_detail":"1f478","tags":["princess","公主","人物"],"emo_type":1},
{"emo_detail":"1f479","tags":["japanese ogre","怪物","人物"],"emo_type":1},
{"emo_detail":"1f47a","tags":["japanese goblin","小妖精","丑小鬼","人物"],"emo_type":1},
{"emo_detail":"1f47b","tags":["ghost","鬼","人物"],"emo_type":1},
{"emo_detail":"1f47c","tags":["baby angel","宝贝天使","人物"],"emo_type":1},
{"emo_detail":"1f47d","tags":["extraterrestrial alien","外星人","人物"],"emo_type":1},
{"emo_detail":"1f47e","tags":["alien monster","外星怪物","怪兽","人物"],"emo_type":1},
{"emo_detail":"1f47f","tags":["imp","小鬼","人物"],"emo_type":1},
{"emo_detail":"1f480","tags":["skull","头骨","人物"],"emo_type":1},
{"emo_detail":"1f481","tags":["information desk person","前台","人物"],"emo_type":1},
{"emo_detail":"1f482","tags":["guardsman","卫兵","人物"],"emo_type":1},
{"emo_detail":"1f483","tags":["dancer","舞者","人物"],"emo_type":1},
{"emo_detail":"1f484","tags":["lipstick","口红","美容"],"emo_type":1},
{"emo_detail":"1f485","tags":["nail polish","指甲油","美容"],"emo_type":1},
{"emo_detail":"1f486","tags":["face massage","脸部按摩","美容"],"emo_type":1},
{"emo_detail":"1f487","tags":["haircut","理发","美容"],"emo_type":1},
{"emo_detail":"1f488","tags":["barber pole","理发店","美容"],"emo_type":1},
{"emo_detail":"1f489","tags":["syringe","注射器","医疗"],"emo_type":1},
{"emo_detail":"1f48a","tags":["pill","药丸","医疗"],"emo_type":1},
{"emo_detail":"1f48b","tags":["kiss mark","红唇","亲一口"],"emo_type":1},
{"emo_detail":"1f48c","tags":["love letter","情书"],"emo_type":1},
{"emo_detail":"1f48d","tags":["ring","戒指","服饰"],"emo_type":1},
{"emo_detail":"1f48e","tags":["gem stone","钻石","服饰"],"emo_type":1},
{"emo_detail":"1f48f","tags":["kiss","亲吻","爱情"],"emo_type":1},
{"emo_detail":"1f490","tags":["bouquet","花束"],"emo_type":1},
{"emo_detail":"1f491","tags":["couple with heart","情侣","夫妇","人物"],"emo_type":1},
{"emo_detail":"1f492","tags":["wedding","婚礼"],"emo_type":1},
{"emo_detail":"1f493","tags":["beating heart","心跳"],"emo_type":1},
{"emo_detail":"1f494","tags":["broken heart","心碎"],"emo_type":1},
{"emo_detail":"1f495","tags":["two hearts","两颗星"],"emo_type":1},
{"emo_detail":"1f496","tags":["sparkling heart","心星"],"emo_type":1},
{"emo_detail":"1f497","tags":["growing heart","爱心"],"emo_type":1},
{"emo_detail":"1f498","tags":["heart with arrow","一见钟情"],"emo_type":1},
{"emo_detail":"1f499","tags":["blue heart","蓝心"],"emo_type":1},
{"emo_detail":"1f49a","tags":["green heart","绿心"],"emo_type":1},
{"emo_detail":"1f49b","tags":["yellow heart","黄心"],"emo_type":1},
{"emo_detail":"1f49c","tags":["purple heart","紫色"],"emo_type":1},
{"emo_detail":"1f49d","tags":["heart with ribbon","丝带心"],"emo_type":1},
{"emo_detail":"1f49e","tags":["revolving hearts","旋转的心"],"emo_type":1},
{"emo_detail":"1f49f","tags":["heart decoration","心装饰"],"emo_type":1},
{"emo_detail":"1f4a0","tags":["diamond shape with a dot inside","钻石心"],"emo_type":1},
{"emo_detail":"1f4a1","tags":["electric light bulb","电灯泡"],"emo_type":1},
{"emo_detail":"1f4a2","tags":["anger symbol","愤怒的象征"],"emo_type":1},
{"emo_detail":"1f4a3","tags":["bomb","炸弹"],"emo_type":1},
{"emo_detail":"1f4a4","tags":["sleeping symbol","沉睡","磕睡"],"emo_type":1},
{"emo_detail":"1f4a5","tags":["collision symbol","碰撞","撞击"],"emo_type":1},
{"emo_detail":"1f4a6","tags":["splashing sweat symbol","水滴飞溅"],"emo_type":1},
{"emo_detail":"1f4a7","tags":["droplet","液滴"],"emo_type":1},
{"emo_detail":"1f4a8","tags":["dash symbol","破折号"],"emo_type":1},
{"emo_detail":"1f4a9","tags":["pile of poo","一坨屎"],"emo_type":1},
{"emo_detail":"1f4aa","tags":["flexed biceps","二头肌"],"emo_type":1},
{"emo_detail":"1f4ab","tags":["dizzy symbol","头晕","晕"],"emo_type":1},
{"emo_detail":"1f4ac","tags":["speech balloon","说话"],"emo_type":1},
{"emo_detail":"1f4ad","tags":["thought balloon","想"],"emo_type":1},
{"emo_detail":"1f4ae","tags":["white flower","白花"],"emo_type":1},
{"emo_detail":"1f4af","tags":["hundred points symbol","100分","一百分","钱"],"emo_type":1},
{"emo_detail":"1f4b0","tags":["money bag","钱袋","钱"],"emo_type":1},
{"emo_detail":"1f4b1","tags":["currency exchange","货币兑换","钱"],"emo_type":1},
{"emo_detail":"1f4b2","tags":["heavy dollar sign","美元","钱"],"emo_type":1},
{"emo_detail":"1f4b3","tags":["credit card","信用卡","钱"],"emo_type":1},
{"emo_detail":"1f4b4","tags":["banknote with yen sign","钞票","钱","钱"],"emo_type":1},
{"emo_detail":"1f4b5","tags":["banknote with dollar sign","美元","钞票","钱","钱"],"emo_type":1},
{"emo_detail":"1f4b6","tags":["banknote with euro sign","欧元","钱"],"emo_type":1},
{"emo_detail":"1f4b7","tags":["banknote with pound sign","英镑","钱"],"emo_type":1},
{"emo_detail":"1f4b8","tags":["money with wings","钞票","钱","钱"],"emo_type":1},
{"emo_detail":"1f4b9","tags":["chart with upwards trend and yen sign","趋势","股票","钱"],"emo_type":1},
{"emo_detail":"1f4ba","tags":["seat","椅子","座椅"],"emo_type":1},
{"emo_detail":"1f4bb","tags":["personal computer","个人电脑","PC","电脑"],"emo_type":1},
{"emo_detail":"1f4bc","tags":["briefcase","公文包"],"emo_type":1},
{"emo_detail":"1f4bd","tags":["minidisc","光碟"],"emo_type":1},
{"emo_detail":"1f4be","tags":["floppy disk","软盘"],"emo_type":1},
{"emo_detail":"1f4bf","tags":["optical disc","光盘"],"emo_type":1},
{"emo_detail":"1f4c0","tags":["dvd","dvd"],"emo_type":1},
{"emo_detail":"1f4c1","tags":["file folder","文件夹"],"emo_type":1},
{"emo_detail":"1f4c2","tags":["open file folder","打开文件夹"],"emo_type":1},
{"emo_detail":"1f4c3","tags":["page with curl","卷曲的纸"],"emo_type":1},
{"emo_detail":"1f4c4","tags":["page facing up","纸"],"emo_type":1},
{"emo_detail":"1f4c5","tags":["calendar","日历"],"emo_type":1},
{"emo_detail":"1f4c6","tags":["tear-off calendar","撕下的日历"],"emo_type":1},
{"emo_detail":"1f4c7","tags":["card index","卡片索引"],"emo_type":1},
{"emo_detail":"1f4c8","tags":["chart with upwards trend","向上趋势","上涨","上升","涨"],"emo_type":1},
{"emo_detail":"1f4c9","tags":["chart with downwards trend","向下趋势","下跌","下降","跌","降"],"emo_type":1},
{"emo_detail":"1f4ca","tags":["bar chart","条形图","柱状图"],"emo_type":1},
{"emo_detail":"1f4cb","tags":["clipboard","剪贴板"],"emo_type":1},
{"emo_detail":"1f4cc","tags":["pushpin","图钉"],"emo_type":1},
{"emo_detail":"1f4cd","tags":["round pushpin","圆图钉"],"emo_type":1},
{"emo_detail":"1f4ce","tags":["paperclip","回形针"],"emo_type":1},
{"emo_detail":"1f4cf","tags":["straight ruler","直尺"],"emo_type":1},
{"emo_detail":"1f4d0","tags":["triangular ruler","三角尺"],"emo_type":1},
{"emo_detail":"1f4d1","tags":["bookmark tabs","书签","标签"],"emo_type":1},
{"emo_detail":"1f4d2","tags":["ledger","分类帐"],"emo_type":1},
{"emo_detail":"1f4d3","tags":["notebook","笔记本"],"emo_type":1},
{"emo_detail":"1f4d4","tags":["notebook with decorative cover","装饰封面的笔记本"],"emo_type":1},
{"emo_detail":"1f4d5","tags":["closed book","合上的书"],"emo_type":1},
{"emo_detail":"1f4d6","tags":["open book","打开的书","书本"],"emo_type":1},
{"emo_detail":"1f4d7","tags":["green book","绿皮书"],"emo_type":1},
{"emo_detail":"1f4d8","tags":["blue book","蓝皮书"],"emo_type":1},
{"emo_detail":"1f4d9","tags":["orange book","橙皮书"],"emo_type":1},
{"emo_detail":"1f4da","tags":["books","书堆","书本","书"],"emo_type":1},
{"emo_detail":"1f4db","tags":["name badge","徽章"],"emo_type":1},
{"emo_detail":"1f4dc","tags":["scroll","滚动"],"emo_type":1},
{"emo_detail":"1f4dd","tags":["memo","备忘录"],"emo_type":1},
{"emo_detail":"1f4de","tags":["telephone receiver","听筒"],"emo_type":1},
{"emo_detail":"1f4df","tags":["pager","寻呼机"],"emo_type":1},
{"emo_detail":"1f4e0","tags":["fax machine","传真机"],"emo_type":1},
{"emo_detail":"1f4e1","tags":["satellite antenna","卫星天线"],"emo_type":1},
{"emo_detail":"1f4e2","tags":["public address loudspeaker","扬声器","喇叭"],"emo_type":1},
{"emo_detail":"1f4e3","tags":["cheering megaphone","扬声器","喇叭"],"emo_type":1},
{"emo_detail":"1f4e4","tags":["outbox tray","发件箱"],"emo_type":1},
{"emo_detail":"1f4e5","tags":["inbox tray","收件箱"],"emo_type":1},
{"emo_detail":"1f4e6","tags":["package","包"],"emo_type":1},
{"emo_detail":"1f4e7","tags":["e-mail symbol","电子邮件"],"emo_type":1},
{"emo_detail":"1f4e8","tags":["incoming envelope","信封"],"emo_type":1},
{"emo_detail":"1f4e9","tags":["envelope with downwards arrow above","收信"],"emo_type":1},
{"emo_detail":"1f4ea","tags":["closed mailbox with lowered flag","邮箱","信箱"],"emo_type":1},
{"emo_detail":"1f4eb","tags":["closed mailbox with raised flag","邮箱","信箱"],"emo_type":1},
{"emo_detail":"1f4ec","tags":["open mailbox with raised flag","邮箱","信箱"],"emo_type":1},
{"emo_detail":"1f4ed","tags":["open mailbox with lowered flag","邮箱","信箱"],"emo_type":1},
{"emo_detail":"1f4ee","tags":["postbox","邮箱","邮筒"],"emo_type":1},
{"emo_detail":"1f4ef","tags":["postal horn","邮差号"],"emo_type":1},
{"emo_detail":"1f4f0","tags":["newspaper","报纸"],"emo_type":1},
{"emo_detail":"1f4f1","tags":["mobile phone","移动电话"],"emo_type":1},
{"emo_detail":"1f4f2","tags":["mobile phone with rightwards arrow at left","打电话"],"emo_type":1},
{"emo_detail":"1f4f3","tags":["vibration mode","震动模式"],"emo_type":1},
{"emo_detail":"1f4f4","tags":["mobile phone off","手机关机"],"emo_type":1},
{"emo_detail":"1f4f5","tags":["no mobile phones","禁用手机"],"emo_type":1},
{"emo_detail":"1f4f6","tags":["antenna with bars","信号"],"emo_type":1},
{"emo_detail":"1f4f7","tags":["camera","相机"],"emo_type":1},
{"emo_detail":"1f4f9","tags":["video camera","摄像机"],"emo_type":1},
{"emo_detail":"1f4fa","tags":["television","电视"],"emo_type":1},
{"emo_detail":"1f4fb","tags":["radio","收音机"],"emo_type":1},
{"emo_detail":"1f4fc","tags":["videocassette","录像带"],"emo_type":1},
{"emo_detail":"1f500","tags":["twisted rightwards arrows","扭曲的向右箭头"],"emo_type":1},
{"emo_detail":"1f501","tags":["clockwise rightwards and leftwards open circle arrows","循环"],"emo_type":1},
{"emo_detail":"1f502","tags":["clockwise rightwards and leftwards open circle arrows with circled one overlay","循环"],"emo_type":1},
{"emo_detail":"1f503","tags":["clockwise downwards and upwards open circle arrows","循环"],"emo_type":1},
{"emo_detail":"1f504","tags":["anticlockwise downwards and upwards open circle arrows","循环"],"emo_type":1},
{"emo_detail":"1f505","tags":["low brightness symbol","低亮度"],"emo_type":1},
{"emo_detail":"1f506","tags":["high brightness symbol","高亮度"],"emo_type":1},
{"emo_detail":"1f507","tags":["speaker with cancellation stroke","静音"],"emo_type":1},
{"emo_detail":"1f509","tags":["speaker with one sound wave","小喇叭"],"emo_type":1},
{"emo_detail":"1f50a","tags":["speaker with three sound waves","大喇叭"],"emo_type":1},
{"emo_detail":"1f50b","tags":["battery","电池"],"emo_type":1},
{"emo_detail":"1f50c","tags":["electric plug","电插头"],"emo_type":1},
{"emo_detail":"1f50d","tags":["left-pointing magnifying glass","放大镜"],"emo_type":1},
{"emo_detail":"1f50e","tags":["right-pointing magnifying glass","放大镜"],"emo_type":1},
{"emo_detail":"1f50f","tags":["lock with ink pen","锁"],"emo_type":1},
{"emo_detail":"1f510","tags":["closed lock with key","锁"],"emo_type":1},
{"emo_detail":"1f511","tags":["key","钥匙"],"emo_type":1},
{"emo_detail":"1f512","tags":["lock","锁"],"emo_type":1},
{"emo_detail":"1f513","tags":["open lock","开锁"],"emo_type":1},
{"emo_detail":"1f514","tags":["bell","铃"],"emo_type":1},
{"emo_detail":"1f515","tags":["bell with cancellation stroke","不响铃"],"emo_type":1},
{"emo_detail":"1f516","tags":["bookmark","书签"],"emo_type":1},
{"emo_detail":"1f517","tags":["link symbol","别针"],"emo_type":1},
{"emo_detail":"1f518","tags":["radio button","按键"],"emo_type":1},
{"emo_detail":"1f519","tags":["back with leftwards arrow above","后退","back"],"emo_type":1},
{"emo_detail":"1f51a","tags":["end with leftwards arrow above","end"],"emo_type":1},
{"emo_detail":"1f51b","tags":["on with exclamation mark with left right arrow above","one"],"emo_type":1},
{"emo_detail":"1f51c","tags":["soon with rightwards arrow above","soon"],"emo_type":1},
{"emo_detail":"1f51d","tags":["top with upwards arrow above","top"],"emo_type":1},
{"emo_detail":"1f51e","tags":["no one under eighteen symbol","十八禁","严禁未成年"],"emo_type":1},
{"emo_detail":"1f51f","tags":["keycap ten","10"],"emo_type":1},
{"emo_detail":"1f520","tags":["input symbol for latin capital letters","ABCD"],"emo_type":1},
{"emo_detail":"1f521","tags":["input symbol for latin small letters","abcd"],"emo_type":1},
{"emo_detail":"1f522","tags":["input symbol for numbers","1234"],"emo_type":1},
{"emo_detail":"1f523","tags":["input symbol for symbols","abc"],"emo_type":1},
{"emo_detail":"1f524","tags":["input symbol for latin letters","符号"],"emo_type":1},
{"emo_detail":"1f525","tags":["fire","火焰"],"emo_type":1},
{"emo_detail":"1f526","tags":["electric torch","手电筒"],"emo_type":1},
{"emo_detail":"1f527","tags":["wrench","扳手"],"emo_type":1},
{"emo_detail":"1f528","tags":["hammer","锤子"],"emo_type":1},
{"emo_detail":"1f529","tags":["nut and bolt","螺母","螺栓"],"emo_type":1},
{"emo_detail":"1f52a","tags":["hocho","水泥刀"],"emo_type":1},
{"emo_detail":"1f52b","tags":["pistol","手枪"],"emo_type":1},
{"emo_detail":"1f52c","tags":["microscope","显微镜"],"emo_type":1},
{"emo_detail":"1f52d","tags":["telescope","望远镜"],"emo_type":1},
{"emo_detail":"1f52e","tags":["crystal ball","水晶球"],"emo_type":1},
{"emo_detail":"1f52f","tags":["six pointed star with middle dot","六角星"],"emo_type":1},
{"emo_detail":"1f530","tags":["japanese symbol for beginner","日语符号"],"emo_type":1},
{"emo_detail":"1f531","tags":["trident emblem","三叉戟"],"emo_type":1},
{"emo_detail":"1f532","tags":["black square button","黑色方形按钮"],"emo_type":1},
{"emo_detail":"1f533","tags":["white square button","白色方形按钮"],"emo_type":1},
{"emo_detail":"1f534","tags":["large red circle","红色圆圈"],"emo_type":1},
{"emo_detail":"1f535","tags":["large blue circle","蓝色圆圈"],"emo_type":1},
{"emo_detail":"1f536","tags":["large orange diamond","大橙钻石"],"emo_type":1},
{"emo_detail":"1f537","tags":["large blue diamond","大蓝钻石"],"emo_type":1},
{"emo_detail":"1f538","tags":["small orange diamond","小橙钻石"],"emo_type":1},
{"emo_detail":"1f539","tags":["small blue diamond","小蓝钻石"],"emo_type":1},
{"emo_detail":"1f53a","tags":["up-pointing red triangle","上"],"emo_type":1},
{"emo_detail":"1f53b","tags":["down-pointing red triangle","下"],"emo_type":1},
{"emo_detail":"1f53c","tags":["up-pointing small red triangle","上"],"emo_type":1},
{"emo_detail":"1f53d","tags":["down-pointing small red triangle","下"],"emo_type":1},
{"emo_detail":"1f550","tags":["clock face one oclock","一点","一点钟"],"emo_type":1},
{"emo_detail":"1f551","tags":["clock face two oclock","两点","两点钟"],"emo_type":1},
{"emo_detail":"1f552","tags":["clock face three oclock","三点","三点钟"],"emo_type":1},
{"emo_detail":"1f553","tags":["clock face four oclock","四点","四点钟"],"emo_type":1},
{"emo_detail":"1f554","tags":["clock face five oclock","五点","五点钟"],"emo_type":1},
{"emo_detail":"1f555","tags":["clock face six oclock","六点","六点钟"],"emo_type":1},
{"emo_detail":"1f556","tags":["clock face seven oclock","七点","七点钟"],"emo_type":1},
{"emo_detail":"1f557","tags":["clock face eight oclock","八点","八点钟"],"emo_type":1},
{"emo_detail":"1f558","tags":["clock face nine oclock","九点","九点钟"],"emo_type":1},
{"emo_detail":"1f559","tags":["clock face ten oclock","十点","十点钟"],"emo_type":1},
{"emo_detail":"1f55a","tags":["clock face eleven oclock","十一点","十一点钟"],"emo_type":1},
{"emo_detail":"1f55b","tags":["clock face twelve oclock","十二点","十二点钟"],"emo_type":1},
{"emo_detail":"1f55c","tags":["clock face one-thirty","一点半"],"emo_type":1},
{"emo_detail":"1f55d","tags":["clock face two-thirty","两点半"],"emo_type":1},
{"emo_detail":"1f55e","tags":["clock face three-thirty","三点半"],"emo_type":1},
{"emo_detail":"1f55f","tags":["clock face four-thirty","四点半"],"emo_type":1},
{"emo_detail":"1f560","tags":["clock face five-thirty","五点半"],"emo_type":1},
{"emo_detail":"1f561","tags":["clock face six-thirty","六点半"],"emo_type":1},
{"emo_detail":"1f562","tags":["clock face seven-thirty","七点半"],"emo_type":1},
{"emo_detail":"1f563","tags":["clock face eight-thirty","八点半"],"emo_type":1},
{"emo_detail":"1f564","tags":["clock face nine-thirty","九点半"],"emo_type":1},
{"emo_detail":"1f565","tags":["clock face ten-thirty","十点半"],"emo_type":1},
{"emo_detail":"1f566","tags":["clock face eleven-thirty","十一点半"],"emo_type":1},
{"emo_detail":"1f567","tags":["grinning face"],"emo_type":1},
{"emo_detail":"1f5fb","tags":["mount fuji","富士山"],"emo_type":1},
{"emo_detail":"1f5fc","tags":["tokyo tower","东京塔"],"emo_type":1},
{"emo_detail":"1f5fd","tags":["statue of liberty","自由女神像","自由女神"],"emo_type":1},
{"emo_detail":"1f5fe","tags":["silhouette of japan","日本"],"emo_type":1},
{"emo_detail":"1f5ff","tags":["moyai","moyai"],"emo_type":1},
{"emo_detail":"1f601","tags":["grinning face with smiling eyes","微笑","呵呵","嘿嘿","小黄脸"],"emo_type":1},
{"emo_detail":"1f602","tags":["face with tears of joy","喜极而泣","小黄脸"],"emo_type":1},
{"emo_detail":"1f603","tags":["smiling face with open mouth","大笑","哈哈","呵呵","嘿嘿","小黄脸"],"emo_type":1},
{"emo_detail":"1f604","tags":["smiling face with open mouth and smiling eyes","大笑","哈哈","呵呵","嘿嘿","小黄脸"],"emo_type":1},
{"emo_detail":"1f605","tags":["smiling face with open mouth and cold sweat","大笑","哈哈","呵呵","嘿嘿","小黄脸"],"emo_type":1},
{"emo_detail":"1f606","tags":["smiling face with open mouth and tightly-closed eyes","大笑","哈哈","呵呵","嘿嘿","小黄脸"],"emo_type":1},
{"emo_detail":"1f607","tags":["smiling face with halo","光环"],"emo_type":1},
{"emo_detail":"1f608","tags":["smiling face with horns"],"emo_type":1},
{"emo_detail":"1f609","tags":["winking face","眨眼","小黄脸"],"emo_type":1},
{"emo_detail":"1f60a","tags":["smiling face with smiling eyes","微笑","呵呵","嘿嘿","小黄脸"],"emo_type":1},
{"emo_detail":"1f60b","tags":["face savouring delicious food","美味","好吃","小黄脸"],"emo_type":1},
{"emo_detail":"1f60c","tags":["relieved face","放松","小黄脸"],"emo_type":1},
{"emo_detail":"1f60d","tags":["smiling face with heart-shaped eyes","爱你","色","小黄脸"],"emo_type":1},
{"emo_detail":"1f60f","tags":["smirking face","傻笑","小黄脸"],"emo_type":1},
{"emo_detail":"1f610","tags":["neutral face"],"emo_type":1},
{"emo_detail":"1f611","tags":["expressionless face","面无表情","小黄脸"],"emo_type":1},
{"emo_detail":"1f612","tags":["unamused face","囧","尴尬","小黄脸"],"emo_type":1},
{"emo_detail":"1f613","tags":["face with cold sweat","冷汗","小黄脸"],"emo_type":1},
{"emo_detail":"1f614","tags":["pensive face","忧郁","小黄脸"],"emo_type":1},
{"emo_detail":"1f615","tags":["confused face","困惑","小黄脸"],"emo_type":1},
{"emo_detail":"1f616","tags":["confounded face","惊慌","小黄脸"],"emo_type":1},
{"emo_detail":"1f617","tags":["kissing face","亲亲","小黄脸"],"emo_type":1},
{"emo_detail":"1f618","tags":["face throwing a kiss","飞吻","亲亲","吻","么么","接吻","小黄脸"],"emo_type":1},
{"emo_detail":"1f619","tags":["kissing face with smiling eyes","亲亲","小黄脸"],"emo_type":1},
{"emo_detail":"1f61a","tags":["kissing face with closed eyes","亲亲","吻","么么","接吻","小黄脸"],"emo_type":1},
{"emo_detail":"1f61b","tags":["face with stuck-out tongue","调皮","吐舌头","小黄脸"],"emo_type":1},
{"emo_detail":"1f61c","tags":["face with stuck-out tongue and winking eye","调皮","吐舌头","眨眼睛","小黄脸"],"emo_type":1},
{"emo_detail":"1f61d","tags":["face with stuck-out tongue and tightly-closed eyes","调皮","吐舌头","小黄脸"],"emo_type":1},
{"emo_detail":"1f61e","tags":["disappointed face","失望","小黄脸"],"emo_type":1},
{"emo_detail":"1f61f","tags":["worried face","担心","小黄脸"],"emo_type":1},
{"emo_detail":"1f620","tags":["angry face","愤怒","小黄脸"],"emo_type":1},
{"emo_detail":"1f621","tags":["pouting face","撅嘴","小黄脸"],"emo_type":1},
{"emo_detail":"1f622","tags":["crying face","哭泣","哭","小黄脸"],"emo_type":1},
{"emo_detail":"1f623","tags":["persevering face","坚持","坚定","小黄脸"],"emo_type":1},
{"emo_detail":"1f624","tags":["face with look of triumph","面对胜利的表情","小黄脸"],"emo_type":1},
{"emo_detail":"1f625","tags":["disappointed but relieved face","失望","小黄脸"],"emo_type":1},
{"emo_detail":"1f626","tags":["frowning face with open mouth","皱眉","小黄脸"],"emo_type":1},
{"emo_detail":"1f627","tags":["anguished face","痛苦","小黄脸"],"emo_type":1},
{"emo_detail":"1f628","tags":["fearful face","可怕","吓人","恐惧","小黄脸"],"emo_type":1},
{"emo_detail":"1f629","tags":["weary face","疲惫","小黄脸"],"emo_type":1},
{"emo_detail":"1f62a","tags":["sleepy face","瞌睡","小黄脸"],"emo_type":1},
{"emo_detail":"1f62b","tags":["tired face","疲惫","累","疲倦","小黄脸"],"emo_type":1},
{"emo_detail":"1f62c","tags":["grimacing face","做鬼脸","小黄脸"],"emo_type":1},
{"emo_detail":"1f62d","tags":["loudly crying face","大哭","小黄脸"],"emo_type":1},
{"emo_detail":"1f62e","tags":["face with open mouth","张嘴","小黄脸"],"emo_type":1},
{"emo_detail":"1f62f","tags":["hushed face","平静","小黄脸"],"emo_type":1},
{"emo_detail":"1f630","tags":["face with open mouth and cold sweat","汗","小黄脸"],"emo_type":1},
{"emo_detail":"1f631","tags":["face screaming in fear","恐惧","小黄脸"],"emo_type":1},
{"emo_detail":"1f632","tags":["astonished face","惊讶","小黄脸"],"emo_type":1},
{"emo_detail":"1f633","tags":["flushed face","激动","小黄脸"],"emo_type":1},
{"emo_detail":"1f634","tags":["sleeping face","沉睡","困","小黄脸"],"emo_type":1},
{"emo_detail":"1f635","tags":["dizzy face","头晕目眩","晕","小黄脸"],"emo_type":1},
{"emo_detail":"1f636","tags":["face without mouth","闭嘴","小黄脸"],"emo_type":1},
{"emo_detail":"1f637","tags":["face with medical mask","生病","小黄脸"],"emo_type":1},
{"emo_detail":"1f638","tags":["grinning cat face with smiling eyes","微笑","小黄脸"],"emo_type":1},
{"emo_detail":"1f639","tags":["cat face with tears of joy","喜极而泣","小黄脸"],"emo_type":1},
{"emo_detail":"1f63a","tags":["smiling cat face with open mouth","大笑","小黄脸"],"emo_type":1},
{"emo_detail":"1f63b","tags":["smiling cat face with heart-shaped eyes","爱你","色","小黄脸"],"emo_type":1},
{"emo_detail":"1f63c","tags":["cat face with wry smile","苦笑","小黄脸"],"emo_type":1},
{"emo_detail":"1f63d","tags":["kissing cat face with closed eyes","接吻","小黄脸"],"emo_type":1},
{"emo_detail":"1f63e","tags":["pouting cat face","撅嘴","小黄脸"],"emo_type":1},
{"emo_detail":"1f63f","tags":["crying cat face","哭泣","小黄脸"],"emo_type":1},
{"emo_detail":"1f640","tags":["weary cat face","疲倦","小黄脸"],"emo_type":1},
{"emo_detail":"1f645","tags":["face with no good gesture","停止","小黄脸"],"emo_type":1},
{"emo_detail":"1f646","tags":["face with ok gesture","OK","小黄脸"],"emo_type":1},
{"emo_detail":"1f647","tags":["person bowing deeply","鞠躬","小黄脸"],"emo_type":1},
{"emo_detail":"1f648","tags":["see-no-evil monkey","不该看","小黄脸"],"emo_type":1},
{"emo_detail":"1f649","tags":["hear-no-evil monkey","不该听","小黄脸"],"emo_type":1},
{"emo_detail":"1f64a","tags":["speak-no-evil monkey","不该说","小黄脸"],"emo_type":1},
{"emo_detail":"1f64b","tags":["happy person raising one hand","打招呼","招手","小黄脸"],"emo_type":1},
{"emo_detail":"1f64c","tags":["person raising both hands in celebration","庆祝","小黄脸"],"emo_type":1},
{"emo_detail":"1f64d","tags":["person frowning","皱眉","小黄脸"],"emo_type":1},
{"emo_detail":"1f64e","tags":["person with pouting face","撅嘴","小黄脸"],"emo_type":1},
{"emo_detail":"1f64f","tags":["person with folded hands","合十"],"emo_type":1},
{"emo_detail":"1f680","tags":["rocket","火箭","交通"],"emo_type":1},
{"emo_detail":"1f681","tags":["helicopter","直升机","交通"],"emo_type":1},
{"emo_detail":"1f682","tags":["steam locomotive","蒸汽车","蒸汽机车","交通"],"emo_type":1},
{"emo_detail":"1f683","tags":["railway car","电车","交通"],"emo_type":1},
{"emo_detail":"1f684","tags":["high-speed train","火车","交通"],"emo_type":1},
{"emo_detail":"1f685","tags":["high-speed train with bullet nose","火车","交通"],"emo_type":1},
{"emo_detail":"1f686","tags":["train","火车","交通"],"emo_type":1},
{"emo_detail":"1f687","tags":["metro","地铁","交通"],"emo_type":1},
{"emo_detail":"1f688","tags":["light rail","轻轨","交通"],"emo_type":1},
{"emo_detail":"1f689","tags":["station","火车站","交通"],"emo_type":1},
{"emo_detail":"1f68a","tags":["tram","电车轨道","煤车","交通"],"emo_type":1},
{"emo_detail":"1f68c","tags":["bus","公共汽车","公交车","交通"],"emo_type":1},
{"emo_detail":"1f68d","tags":["oncoming bus","公共汽车","公交车","交通"],"emo_type":1},
{"emo_detail":"1f68e","tags":["trolleybus","无轨电车","交通"],"emo_type":1},
{"emo_detail":"1f68f","tags":["bus stop","公共汽车站","公交车站","交通"],"emo_type":1},
{"emo_detail":"1f690","tags":["minibus","中巴车","迷你巴士","交通"],"emo_type":1},
{"emo_detail":"1f691","tags":["ambulance","救护车","交通"],"emo_type":1},
{"emo_detail":"1f692","tags":["fire engine","消防车","交通"],"emo_type":1},
{"emo_detail":"1f693","tags":["police car","警车","交通"],"emo_type":1},
{"emo_detail":"1f694","tags":["oncoming police car","警车","交通"],"emo_type":1},
{"emo_detail":"1f695","tags":["taxi","出租车","交通"],"emo_type":1},
{"emo_detail":"1f696","tags":["oncoming taxi","出租车","交通"],"emo_type":1},
{"emo_detail":"1f697","tags":["automobile","汽车","轿车","交通"],"emo_type":1},
{"emo_detail":"1f698","tags":["oncoming automobile","汽车","交通"],"emo_type":1},
{"emo_detail":"1f699","tags":["recreational vehicle","休闲车","交通"],"emo_type":1},
{"emo_detail":"1f69a","tags":["delivery truck","货车","卡车","交通"],"emo_type":1},
{"emo_detail":"1f69b","tags":["articulated lorry","货车","卡车","交通"],"emo_type":1},
{"emo_detail":"1f69c","tags":["tractor","拖拉机","交通"],"emo_type":1},
{"emo_detail":"1f69d","tags":["monorail","单轨铁路","交通"],"emo_type":1},
{"emo_detail":"1f69e","tags":["mountain railway","山区铁路","交通"],"emo_type":1},
{"emo_detail":"1f69f","tags":["suspension railway","悬索铁路","交通"],"emo_type":1},
{"emo_detail":"1f6a0","tags":["mountain cableway","索道","缆车","交通"],"emo_type":1},
{"emo_detail":"1f6a1","tags":["aerial tramway","索道","缆车","交通"],"emo_type":1},
{"emo_detail":"1f6a2","tags":["ship","船","交通"],"emo_type":1},
{"emo_detail":"1f6a3","tags":["rowboat","小船","交通"],"emo_type":1},
{"emo_detail":"1f6a4","tags":["speedboat","快艇","交通"],"emo_type":1},
{"emo_detail":"1f6a5","tags":["horizontal traffic light","红绿灯","交通灯","交通"],"emo_type":1},
{"emo_detail":"1f6a6","tags":["vertical traffic light","红绿灯","交通灯","交通"],"emo_type":1},
{"emo_detail":"1f6a7","tags":["construction sign","施工","交通"],"emo_type":1},
{"emo_detail":"1f6a8","tags":["police cars revolving light","警车灯","交通"],"emo_type":1},
{"emo_detail":"1f6a9","tags":["triangular flag on post","三角旗"],"emo_type":1},
{"emo_detail":"1f6aa","tags":["door","门"],"emo_type":1},
{"emo_detail":"1f6ab","tags":["no entry sign","禁止"],"emo_type":1},
{"emo_detail":"1f6ac","tags":["smoking symbol","吸烟"],"emo_type":1},
{"emo_detail":"1f6ad","tags":["no smoking symbol","禁止吸烟"],"emo_type":1},
{"emo_detail":"1f6ae","tags":["put litter in its place symbol","垃圾箱"],"emo_type":1},
{"emo_detail":"1f6af","tags":["do not litter symbol","禁止乱扔垃圾"],"emo_type":1},
{"emo_detail":"1f6b0","tags":["potable water symbol","饮用水"],"emo_type":1},
{"emo_detail":"1f6b1","tags":["non-potable water symbol","非饮用水"],"emo_type":1},
{"emo_detail":"1f6b2","tags":["bicycle","自行车","交通"],"emo_type":1},
{"emo_detail":"1f6b3","tags":["no bicycles","禁止自行车通行","交通"],"emo_type":1},
{"emo_detail":"1f6b4","tags":["bicyclist","自行车手","骑自行车的人","交通"],"emo_type":1},
{"emo_detail":"1f6b5","tags":["mountain bicyclist","山地自行车","山地自行车手","交通"],"emo_type":1},
{"emo_detail":"1f6b6","tags":["pedestrian","行人","步行","交通"],"emo_type":1},
{"emo_detail":"1f6b7","tags":["no pedestrians","禁止通行","交通"],"emo_type":1},
{"emo_detail":"1f6b8","tags":["children crossing","小孩过马路","交通"],"emo_type":1},
{"emo_detail":"1f6b9","tags":["mens symbol","男","人物"],"emo_type":1},
{"emo_detail":"1f6ba","tags":["womens symbol","女","人物"],"emo_type":1},
{"emo_detail":"1f6bb","tags":["restroom","洗手间","厕所"],"emo_type":1},
{"emo_detail":"1f6bc","tags":["baby symbol","婴儿","婴儿的象征"],"emo_type":1},
{"emo_detail":"1f6bd","tags":["toilet","马桶"],"emo_type":1},
{"emo_detail":"1f6be","tags":["water closet","厕所","洗手间"],"emo_type":1},
{"emo_detail":"1f6bf","tags":["shower","洗澡"],"emo_type":1},
{"emo_detail":"1f6c0","tags":["bath","洗澡"],"emo_type":1},
{"emo_detail":"1f6c1","tags":["bathtub","洗澡"],"emo_type":1},
{"emo_detail":"1f6c2","tags":["passport control","护照"],"emo_type":1},
{"emo_detail":"1f6c3","tags":["customs","海关"],"emo_type":1},
{"emo_detail":"1f6c4","tags":["baggage claim","行李"],"emo_type":1},
{"emo_detail":"1f6c5","tags":["left luggage","行李寄存"],"emo_type":1},
{"emo_detail":"203c","tags":["double exclamation mark","感叹号","!!"],"emo_type":1},
{"emo_detail":"2049","tags":["exclamation question mark"],"emo_type":1},
{"emo_detail":"2122","tags":["trade mark sign","贸易"],"emo_type":1},
{"emo_detail":"2139","tags":["information source","信息"],"emo_type":1},
{"emo_detail":"2194","tags":["left right arrow","左右"],"emo_type":1},
{"emo_detail":"2195","tags":["up down arrow","上下"],"emo_type":1},
{"emo_detail":"2196","tags":["north west arrow","西北"],"emo_type":1},
{"emo_detail":"2197","tags":["north east arrow","东北"],"emo_type":1},
{"emo_detail":"2198","tags":["south east arrow","东南"],"emo_type":1},
{"emo_detail":"2199","tags":["south west arrow","西南"],"emo_type":1},
{"emo_detail":"21a9","tags":["leftwards arrow with hook","左转"],"emo_type":1},
{"emo_detail":"21aa","tags":["rightwards arrow with hook","右转"],"emo_type":1},
{"emo_detail":"231a","tags":["watch","手表"],"emo_type":1},
{"emo_detail":"231b","tags":["hourglass","沙漏"],"emo_type":1},
{"emo_detail":"2.30E+10","tags":["black right-pointing double triangle","快进"],"emo_type":1},
{"emo_detail":"23ea","tags":["black left-pointing double triangle","快退"],"emo_type":1},
{"emo_detail":"23eb","tags":["black up-pointing double triangle","上"],"emo_type":1},
{"emo_detail":"23ec","tags":["black down-pointing double triangle","下"],"emo_type":1},
{"emo_detail":"23f0","tags":["alarm clock","闹钟"],"emo_type":1},
{"emo_detail":"23f3","tags":["hourglass with flowing sand","沙漏"],"emo_type":1},
{"emo_detail":"24c2","tags":["circled latin capital letter m","M"],"emo_type":1},
{"emo_detail":"25aa","tags":["black small square","黑方形"],"emo_type":1},
{"emo_detail":"25ab","tags":["white small square","白方形"],"emo_type":1},
{"emo_detail":"25b6","tags":["black right-pointing triangle","前进"],"emo_type":1},
{"emo_detail":"25c0","tags":["black left-pointing triangle","后退"],"emo_type":1},
{"emo_detail":"25fb","tags":["white medium square","黑方形"],"emo_type":1},
{"emo_detail":"25fc","tags":["black medium square","白方形"],"emo_type":1},
{"emo_detail":"25fd","tags":["white medium small square","黑方形"],"emo_type":1},
{"emo_detail":"25fe","tags":["black medium small square","白方形"],"emo_type":1},
{"emo_detail":"2600","tags":["black sun with rays","太阳"],"emo_type":1},
{"emo_detail":"2601","tags":["cloud","云","多云"],"emo_type":1},
{"emo_detail":"260e","tags":["black telephone","电话"],"emo_type":1},
{"emo_detail":"2611","tags":["ballot box with check","正确","对的"],"emo_type":1},
{"emo_detail":"2614","tags":["umbrella with rain drops","雨伞"],"emo_type":1},
{"emo_detail":"2615","tags":["hot beverage","咖啡","茶","饮料"],"emo_type":1},
{"emo_detail":"261d","tags":["white up pointing index"],"emo_type":1},
{"emo_detail":"263a","tags":["white smiling face","微笑"],"emo_type":1},
{"emo_detail":"2648","tags":["aries","白羊座","牧羊座","星座"],"emo_type":1},
{"emo_detail":"2649","tags":["taurus","金牛座","金牛","星座"],"emo_type":1},
{"emo_detail":"264a","tags":["gemini","双子座","双子","星座"],"emo_type":1},
{"emo_detail":"264b","tags":["cancer","巨蟹座","巨蟹","星座"],"emo_type":1},
{"emo_detail":"264c","tags":["leo","狮子座","星座"],"emo_type":1},
{"emo_detail":"264d","tags":["virgo","处女座","星座"],"emo_type":1},
{"emo_detail":"264e","tags":["libra","天秤座","天秤","星座"],"emo_type":1},
{"emo_detail":"264f","tags":["scorpius","天蝎座","天蝎","星座"],"emo_type":1},
{"emo_detail":"2650","tags":["sagittarius","射手座","射手座","星座"],"emo_type":1},
{"emo_detail":"2651","tags":["capricorn","摩羯座","摩羯","星座"],"emo_type":1},
{"emo_detail":"2652","tags":["aquarius","水瓶座","水瓶座","星座"],"emo_type":1},
{"emo_detail":"2653","tags":["pisces","双鱼座","双鱼","星座"],"emo_type":1},
{"emo_detail":"2660","tags":["black spade suit","黑桃"],"emo_type":1},
{"emo_detail":"2663","tags":["black club suit","梅花"],"emo_type":1},
{"emo_detail":"2665","tags":["black heart suit","红桃"],"emo_type":1},
{"emo_detail":"2666","tags":["black diamond suit","方块"],"emo_type":1},
{"emo_detail":"2668","tags":["hot springs","温泉"],"emo_type":1},
{"emo_detail":"267b","tags":["black universal recycling symbol","循环利用"],"emo_type":1},
{"emo_detail":"267f","tags":["wheelchair symbol","轮椅"],"emo_type":1},
{"emo_detail":"2693","tags":["anchor","锚"],"emo_type":1},
{"emo_detail":"26a0","tags":["warning sign","警告"],"emo_type":1},
{"emo_detail":"26a1","tags":["high voltage sign","闪电"],"emo_type":1},
{"emo_detail":"26aa","tags":["medium white circle","白圆形"],"emo_type":1},
{"emo_detail":"26ab","tags":["medium black circle","黑圆形"],"emo_type":1},
{"emo_detail":"26bd","tags":["soccer ball","足球"],"emo_type":1},
{"emo_detail":"26be","tags":["baseball","棒球"],"emo_type":1},
{"emo_detail":"26c4","tags":["snowman without snow","雪人"],"emo_type":1},
{"emo_detail":"26c5","tags":["sun behind cloud","多云"],"emo_type":1},
{"emo_detail":"26ce","tags":["ophiuchus","蛇夫座"],"emo_type":1},
{"emo_detail":"26d4","tags":["no entry","禁止通行"],"emo_type":1},
{"emo_detail":"26ea","tags":["church","教堂"],"emo_type":1},
{"emo_detail":"26f2","tags":["fountain","喷泉"],"emo_type":1},
{"emo_detail":"26f3","tags":["flag in hole","高尔夫"],"emo_type":1},
{"emo_detail":"26f5","tags":["sailboat","帆船","码头"],"emo_type":1},
{"emo_detail":"26fa","tags":["tent","帐篷"],"emo_type":1},
{"emo_detail":"26fd","tags":["fuel pump","加油"],"emo_type":1},
{"emo_detail":"2702","tags":["black scissors","剪刀"],"emo_type":1},
{"emo_detail":"2705","tags":["white heavy check mark","正确","对的"],"emo_type":1},
{"emo_detail":"2708","tags":["airplane","飞机"],"emo_type":1},
{"emo_detail":"2709","tags":["envelope","信封"],"emo_type":1},
{"emo_detail":"270a","tags":["raised fist","高举的拳头"],"emo_type":1},
{"emo_detail":"270b","tags":["raised hand","举起手"],"emo_type":1},
{"emo_detail":"270c","tags":["victory hand","胜利"],"emo_type":1},
{"emo_detail":"270f","tags":["pencil","铅笔"],"emo_type":1},
{"emo_detail":"2712","tags":["black nib","钢笔"],"emo_type":1},
{"emo_detail":"2714","tags":["heavy check mark","正确","对"],"emo_type":1},
{"emo_detail":"2716","tags":["heavy multiplication x","错误","错","叉"],"emo_type":1},
{"emo_detail":"2728","tags":["sparkles","火花"],"emo_type":1},
{"emo_detail":"2733","tags":["eight spoked asterisk","八轮辐星号"],"emo_type":1},
{"emo_detail":"2734","tags":["eight pointed black star","八尖黑星"],"emo_type":1},
{"emo_detail":"2744","tags":["snowflake","雪花"],"emo_type":1},
{"emo_detail":"2747","tags":["sparkle","雪花"],"emo_type":1},
{"emo_detail":"274c","tags":["cross mark","叉"],"emo_type":1},
{"emo_detail":"274e","tags":["negative squared cross mark","叉"],"emo_type":1},
{"emo_detail":"2753","tags":["black question mark ornament","问号","疑问"],"emo_type":1},
{"emo_detail":"2754","tags":["white question mark ornament","问号","疑问"],"emo_type":1},
{"emo_detail":"2755","tags":["white exclamation mark ornament","惊叹号","惊叹"],"emo_type":1},
{"emo_detail":"2757","tags":["heavy exclamation mark symbol","惊叹号","惊叹"],"emo_type":1},
{"emo_detail":"2764","tags":["heavy black heart","心"],"emo_type":1},
{"emo_detail":"2795","tags":["heavy plus sign","加","+"],"emo_type":1},
{"emo_detail":"2796","tags":["heavy minus sign","减","-"],"emo_type":1},
{"emo_detail":"2797","tags":["heavy division sign","除"],"emo_type":1},
{"emo_detail":"27a1","tags":["black rightwards arrow","箭头"],"emo_type":1},
{"emo_detail":"27b0","tags":["curly loop","卷曲的环"],"emo_type":1},
{"emo_detail":"27bf","tags":["double curly loop","双环"],"emo_type":1},
{"emo_detail":"2934","tags":["arrow pointing rightwards then curving upwards","向上"],"emo_type":1},
{"emo_detail":"2935","tags":["arrow pointing rightwards then curving downwards","向下"],"emo_type":1},
{"emo_detail":"2b05","tags":["leftwards black arrow","向左"],"emo_type":1},
{"emo_detail":"2b06","tags":["upwards black arrow","向上"],"emo_type":1},
{"emo_detail":"2b07","tags":["downwards black arrow","向下"],"emo_type":1},
{"emo_detail":"2b1b","tags":["black large square","大黑方形"],"emo_type":1},
{"emo_detail":"2b1c","tags":["white large square","大白方形"],"emo_type":1},
{"emo_detail":"2b50","tags":["white medium star","星星"],"emo_type":1},
{"emo_detail":"2b55","tags":["heavy large circle","圆圈"],"emo_type":1},
{"emo_detail":"3030","tags":["wavy dash","波浪线"],"emo_type":1},
{"emo_detail":"303d","tags":["part alternation mark","歌记号"],"emo_type":1},
{"emo_detail":"3297","tags":["circled ideograph congratulation","祝"],"emo_type":1},
{"emo_detail":"3299","tags":["circled ideograph secret","秘"],"emo_type":1}]